const colors = {
  light: {
    background: '#F8FAFC',
    foreground: '#0F172A',
    card: '#FFFFFF',
    cardForeground: '#0F172A',
    primary: '#FF6B00',
    primaryForeground: '#FFFFFF',
    secondary: '#E2E8F0',
    secondaryForeground: '#0F172A',
    muted: '#F1F5F9',
    mutedForeground: '#64748B',
    accent: '#DBEAFE',
    accentForeground: '#0F172A',
    destructive: '#EF4444',
    destructiveForeground: '#FFFFFF',
    success: '#10B981',
    successForeground: '#FFFFFF',
    warning: '#F59E0B',
    warningForeground: '#FFFFFF',
    na: '#94A3B8',
    naForeground: '#FFFFFF',
    border: '#E2E8F0',
    input: '#E2E8F0',
    header: '#0F172A',
    headerForeground: '#FFFFFF',
  },
  dark: {
    background: '#020617',
    foreground: '#F8FAFC',
    card: '#0F172A',
    cardForeground: '#F8FAFC',
    primary: '#FF6B00',
    primaryForeground: '#FFFFFF',
    secondary: '#1E293B',
    secondaryForeground: '#F8FAFC',
    muted: '#0F172A',
    mutedForeground: '#94A3B8',
    accent: '#1E40AF',
    accentForeground: '#F8FAFC',
    destructive: '#7F1D1D',
    destructiveForeground: '#F8FAFC',
    success: '#065F46',
    successForeground: '#F8FAFC',
    warning: '#92400E',
    warningForeground: '#F8FAFC',
    na: '#334155',
    naForeground: '#F8FAFC',
    border: '#1E293B',
    input: '#1E293B',
    header: '#020617',
    headerForeground: '#F8FAFC',
  },
  radius: 8,
};

export default colors;
